### ISSUE TITLE
App Crash on enter of  "x=1"

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/SURGEgrapher#19]
First I would like to graph that... Vertical Asymptotes!  And we should do some work making sure the user enters something that is graphable and not crash.  Not robust enough yet.

![image](https://user-images.githubusercontent.com/4535729/28852583-1095b394-76df-11e7-9609-757c33332d2a.png)

**Comment by johnRedden** [comment]
1/sin^2(x) seems to be an issue...  works like this though 1/(sin x)^2.

sin^2 x showing difficulty.

**Comment by johnRedden** [comment]
ERROR: type in e^2x and it displays as exponent but graphs as linear e^2 *x
![image](https://user-images.githubusercontent.com/4535729/28852873-51d4747e-76e1-11e7-9af0-95976574098b.png)

**Comment by johnRedden** [comment]
1/abs(x) graphs correctly but does not display.  Also abs(x) graphs but does not display either.
![image](https://user-images.githubusercontent.com/4535729/28886178-5dbedbbc-776d-11e7-976a-3895b54f801e.png)

**Comment by pgonzbecer** [comment]
Kinked out all these bugs.
