### ISSUE TITLE
Too Many Buttons

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/SURGEgrapher#7]
We should devise a UI with at most 3 buttons... no buttons on graph would be ideal.  Graphicus Maximus!

**Comment by johnRedden** [comment]
We seemed to settle on a one button solution... on the main page... small top left hand corner and out of the way would be best.

**Comment by mecharmor** [comment]
ok. I will experiment with some UI ideas for this

**Comment by mecharmor** [comment]
Button quantity decreased
